import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {URL} from 'node:url';

const env=process.env,port=Number(env.PORT||10000),base=(env.PUBLIC_BASE_URL||`http://localhost:${port}`).replace(/\/$/,''),graphVersion=env.META_GRAPH_VERSION||'v23.0';
const graphBase=`https://graph.facebook.com/${graphVersion}`,dataFile=env.DATA_FILE||path.join(process.cwd(),'pulsebar-connect.json');
const json=(res,code,body)=>{res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(body))};
const deviceKeys=()=>{try{return JSON.parse(env.DEVICE_KEYS||'{}')}catch{return{}}};
const authorized=(req,deviceId)=>{const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const expected=deviceKeys()[deviceId];return !!expected&&token.length===expected.length&&crypto.timingSafeEqual(Buffer.from(token),Buffer.from(expected))};
const required=()=>['META_APP_ID','META_APP_SECRET','STATE_SECRET','DATA_ENCRYPTION_KEY'].filter(k=>!env[k]);
const encryptionKey=()=>crypto.createHash('sha256').update(env.DATA_ENCRYPTION_KEY||'development-only').digest();
export function seal(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',encryptionKey(),iv),body=Buffer.concat([cipher.update(JSON.stringify(value)),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64url')}
export function open(value){const raw=Buffer.from(value,'base64url'),decipher=crypto.createDecipheriv('aes-256-gcm',encryptionKey(),raw.subarray(0,12));decipher.setAuthTag(raw.subarray(12,28));return JSON.parse(Buffer.concat([decipher.update(raw.subarray(28)),decipher.final()]).toString())}
const readStore=()=>{try{return JSON.parse(fs.readFileSync(dataFile,'utf8'))}catch{return{devices:{}}}};
const writeStore=data=>{fs.mkdirSync(path.dirname(dataFile),{recursive:true});const tmp=`${dataFile}.tmp`;fs.writeFileSync(tmp,JSON.stringify(data,null,2),{mode:0o600});fs.renameSync(tmp,dataFile)};
const signState=deviceId=>{const payload=Buffer.from(JSON.stringify({deviceId,exp:Date.now()+10*60*1000})).toString('base64url'),sig=crypto.createHmac('sha256',env.STATE_SECRET).update(payload).digest('base64url');return`${payload}.${sig}`};
const verifyState=value=>{const[payload,sig]=String(value||'').split('.'),expected=crypto.createHmac('sha256',env.STATE_SECRET).update(payload||'').digest('base64url');if(!sig||sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))throw Error('Invalid state');const state=JSON.parse(Buffer.from(payload,'base64url'));if(state.exp<Date.now())throw Error('Expired state');return state};
async function graph(pathname,token){const separator=pathname.includes('?')?'&':'?';const response=await fetch(`${graphBase}${pathname}${separator}access_token=${encodeURIComponent(token)}`,{headers:{Accept:'application/json'}}),body=await response.json();if(!response.ok||body.error)throw Error(body.error?.message||`Meta request failed (${response.status})`);return body}
async function metaFetch(pathname){const response=await fetch(`${graphBase}${pathname}`,{headers:{Accept:'application/json'}}),body=await response.json();if(!response.ok||body.error)throw Error(body.error?.message||`Meta request failed (${response.status})`);return body}
async function exchange(code){const query=new URLSearchParams({client_id:env.META_APP_ID,client_secret:env.META_APP_SECRET,redirect_uri:`${base}/oauth/meta/callback`,code});const short=await metaFetch(`/oauth/access_token?${query}`),longQuery=new URLSearchParams({grant_type:'fb_exchange_token',client_id:env.META_APP_ID,client_secret:env.META_APP_SECRET,fb_exchange_token:short.access_token});const long=await metaFetch(`/oauth/access_token?${longQuery}`);return long.access_token}
async function discover(userToken){const fields='id,name,access_token,fan_count,followers_count,instagram_business_account{id,username,followers_count,media_count}';const result=await graph(`/me/accounts?fields=${encodeURIComponent(fields)}`,userToken);if(!result.data?.length)throw Error('No Facebook Page was granted');return result.data[0]}
const latestValue=data=>Array.isArray(data?.data)&&data.data[0]?.values?.length?Number(data.data[0].values.at(-1).value||0):0;
async function metrics(record){const saved=open(record.secret),page=await graph(`/${saved.pageId}?fields=fan_count,followers_count`,saved.pageToken);let instagram=null,facebookViews=0,instagramViews=0,warnings=[];try{facebookViews=latestValue(await graph(`/${saved.pageId}/insights?metric=page_media_view&period=day`,saved.pageToken))}catch(e){warnings.push(`Facebook views unavailable: ${e.message}`)}if(saved.instagramId){instagram=await graph(`/${saved.instagramId}?fields=username,followers_count,media_count`,saved.pageToken);try{instagramViews=latestValue(await graph(`/${saved.instagramId}/insights?metric=views&period=day`,saved.pageToken))}catch(e){warnings.push(`Instagram views unavailable: ${e.message}`)}}return{facebook:{connected:true,name:saved.pageName,followers:Number(page.followers_count??page.fan_count??0),views:facebookViews},instagram:{connected:!!instagram,username:instagram?.username||'',followers:Number(instagram?.followers_count||0),views:instagramViews},updatedAt:new Date().toISOString(),warnings}}

export async function handler(req,res){const url=new URL(req.url,base);if(url.pathname==='/health')return json(res,200,{ok:true,configured:required().length===0});if(url.pathname==='/privacy')return json(res,200,{service:'PulseBar Connect',privacy:'Stores encrypted platform tokens only for the connected PulseBar device. Contact the seller to request deletion.'});if(url.pathname==='/data-deletion')return json(res,200,{instructions:'Disconnect the account in Meta and contact the PulseBar seller with the device ID to delete stored connection data.'});if(url.pathname==='/oauth/meta/callback'){try{const{deviceId}=verifyState(url.searchParams.get('state')),token=await exchange(url.searchParams.get('code')),page=await discover(token),store=readStore();store.devices[deviceId]={secret:seal({pageId:page.id,pageName:page.name,pageToken:page.access_token,instagramId:page.instagram_business_account?.id||''}),connectedAt:new Date().toISOString()};writeStore(store);res.writeHead(302,{Location:`${base}/connected`});return res.end()}catch(e){return json(res,400,{error:e.message})}}if(url.pathname==='/connected'){res.writeHead(200,{'Content-Type':'text/html'});return res.end('<!doctype html><title>PulseBar connected</title><h1>Connected</h1><p>Facebook and Instagram are now linked. You may close this tab.</p>')}const deviceId=url.searchParams.get('deviceId')||'';if(!authorized(req,deviceId))return json(res,401,{error:'Invalid device credentials'});if(url.pathname==='/v1/connect/meta'){const missing=required();if(missing.length)return json(res,503,{error:`Server configuration missing: ${missing.join(', ')}`});const auth=new URL('https://www.facebook.com/dialog/oauth');auth.search=new URLSearchParams({client_id:env.META_APP_ID,redirect_uri:`${base}/oauth/meta/callback`,state:signState(deviceId),response_type:'code',scope:'pages_show_list,pages_read_engagement,read_insights,instagram_basic,instagram_manage_insights'});return json(res,200,{url:auth.toString(),expiresIn:600})}if(url.pathname==='/v1/metrics'){const record=readStore().devices[deviceId];if(!record)return json(res,404,{error:'No Meta account connected'});try{return json(res,200,await metrics(record))}catch(e){return json(res,502,{error:e.message})}}if(url.pathname==='/v1/disconnect'&&req.method==='DELETE'){const store=readStore();delete store.devices[deviceId];writeStore(store);return json(res,200,{disconnected:true})}return json(res,404,{error:'Not found'})}

if(process.env.NODE_ENV!=='test')http.createServer((req,res)=>handler(req,res).catch(e=>json(res,500,{error:e.message}))).listen(port,()=>console.log(`PulseBar Connect listening on ${port}`));
