#include "display/PlaylistService.h"
#include <ArduinoJson.h>

static const char* IDS[PlaylistService::SCENE_COUNT]={"youtubeSubscribers","youtubeViews","facebookFollowers","facebookViews","instagramFollowers","instagramViews","time"};
void PlaylistService::begin(){store_.begin("playlist",false);uint8_t mask=store_.getUChar("mask",0x7F);for(uint8_t i=0;i<SCENE_COUNT;i++)enabled_[i]=mask&(1<<i);use24Hour_=store_.getBool("clock24",true);durationSeconds_=constrain(store_.getUChar("duration",8),2,60);transition_=store_.getString("transition","instant");}
uint8_t PlaylistService::next(uint8_t current)const{for(uint8_t step=1;step<=SCENE_COUNT;step++){uint8_t candidate=(current+step)%SCENE_COUNT;if(enabled_[candidate])return candidate;}return 6;}
String PlaylistService::toJson()const{JsonDocument d;d["clockFormat"]=use24Hour_?"24":"12";d["durationSeconds"]=durationSeconds_;d["transition"]=transition_;JsonArray scenes=d["scenes"].to<JsonArray>();for(uint8_t i=0;i<SCENE_COUNT;i++){JsonObject s=scenes.add<JsonObject>();s["id"]=IDS[i];s["enabled"]=enabled_[i];}String out;serializeJson(d,out);return out;}
bool PlaylistService::updateFromJson(const String& json){JsonDocument d;if(deserializeJson(d,json)||!d["scenes"].is<JsonArray>())return false;use24Hour_=String(d["clockFormat"]|"24")!="12";durationSeconds_=constrain(d["durationSeconds"]|8,2,60);String requested=d["transition"]|"instant";const char* allowed[]={"instant","slideLeft","slideRight","fade","wipeLeft","wipeRight","dissolve","blink"};transition_="instant";for(const char* value:allowed)if(requested==value)transition_=value;bool next[SCENE_COUNT]={};for(JsonObject item:d["scenes"].as<JsonArray>()){String id=item["id"]|"";for(uint8_t i=0;i<SCENE_COUNT;i++)if(id==IDS[i])next[i]=item["enabled"]|false;}bool any=false;for(uint8_t i=0;i<SCENE_COUNT;i++){enabled_[i]=next[i];any|=next[i];}if(!any)enabled_[6]=true;save();return true;}
void PlaylistService::save(){uint8_t mask=0;for(uint8_t i=0;i<SCENE_COUNT;i++)if(enabled_[i])mask|=1<<i;store_.putUChar("mask",mask);store_.putBool("clock24",use24Hour_);store_.putUChar("duration",durationSeconds_);store_.putString("transition",transition_);}
