#pragma once
#include <Arduino.h>

const char WEB_UI[] PROGMEM = R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PulseBar</title><style>
:root{color-scheme:dark;--ink:#f7f7fb;--muted:#9999ae;--card:#17171f;--line:#292936;--accent:#ff4d91}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#302043 0,transparent 32%),#0b0b10;color:var(--ink);font:15px Inter,system-ui,sans-serif}.shell{max-width:1120px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}.brand{font-size:23px;font-weight:800}.brand i{display:inline-block;width:12px;height:12px;background:var(--accent);border-radius:4px;box-shadow:14px 0 #55dfff;margin-right:20px}.top-right{display:flex;align-items:center;gap:10px}.pill{padding:8px 12px;background:#183325;color:#76efaa;border-radius:99px;font-size:12px}.wifi{width:28px;height:22px;fill:none;stroke:#777789;stroke-width:2.3;stroke-linecap:round}.wifi.good{stroke:#76efaa}.wifi.weak{stroke:#ffc76b}.layout{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.card{background:linear-gradient(145deg,#1b1b25,#131319);border:1px solid var(--line);border-radius:20px;padding:20px;box-shadow:0 12px 40px #0004}.eyebrow{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:1.4px}.matrix{display:grid;grid-template-columns:repeat(32,1fr);gap:2px;background:#08080b;padding:8px;border-radius:10px;margin:14px 0 20px}.px{aspect-ratio:1;background:#20202a;border-radius:1px}.px.on{background:var(--accent);box-shadow:0 0 7px var(--accent)}input,select{width:100%;accent-color:var(--accent);background:#101016;border:1px solid var(--line);color:white;border-radius:10px;padding:11px}button{border:1px solid #353545;background:#23232e;color:white;border-radius:12px;padding:12px;cursor:pointer}button.primary{border:0;background:linear-gradient(90deg,var(--accent),#aa5cff)}.brightness{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.palette{display:none;grid-template-columns:repeat(6,32px);gap:9px;margin:12px 0}.palette.open{display:grid}.swatch{width:32px;height:32px;border-radius:50%;padding:0;border:2px solid #ffffff33}.scenes{display:grid;gap:11px;margin:16px 0}.scene{display:flex;align-items:center;gap:10px}.scene input{width:auto}.platforms{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:18px 0 10px}.platform{min-height:58px}.platform.active{border-color:var(--accent);background:#30202c}.platform svg{width:27px;height:27px}.account-row{display:grid;grid-template-columns:1fr auto;gap:9px}.hint{color:var(--muted);line-height:1.5}.setup{position:fixed;inset:0;background:#09090df2;z-index:10;display:none;place-items:center;padding:18px}.setup.show{display:grid}.setup .card{width:min(480px,100%)}.field{display:grid;gap:6px;margin:14px 0}.error{color:#ff829d;min-height:20px}@media(max-width:760px){.layout{grid-template-columns:1fr}.shell{padding:16px}.matrix{gap:1px;padding:5px}.platforms,.account-row{grid-template-columns:1fr}}
.category{border-top:1px solid var(--line);padding:16px 0}.category:first-child{border:0;padding-top:4px}.category-head{display:grid;grid-template-columns:1fr 112px;gap:12px;align-items:center}.category h3{margin:0 0 9px;font-size:16px}.mini{display:grid;grid-template-columns:repeat(32,1fr);gap:1px;background:#08080b;padding:4px;border-radius:7px}.mini i{aspect-ratio:1;background:#24242f}.mini i.on{background:var(--accent)}.choice{display:flex;align-items:center;gap:9px;margin:8px 0}.choice input{appearance:none;width:18px;height:18px;padding:0;border:2px solid #656579;border-radius:50%;display:grid;place-items:center}.choice input:checked{border:5px solid var(--accent);background:white}.format{display:flex;gap:14px;margin-top:8px}
.platform{min-height:86px}.platform svg{width:48px;height:48px}.display-tools{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.tool{display:grid;gap:6px}.tool button{width:100%}
</style></head><body>
<div class="setup" id="setup"><form class="card" id="setupForm"><div class="brand"><i></i>PulseBar</div><h1>Let’s get connected</h1><p class="hint">Choose Wi-Fi and name this PulseBar.</p><div class="field"><label>Wi-Fi network</label><select id="setupSsid" required><option>Searching…</option></select></div><div class="field"><label>Password</label><input id="setupPassword" type="password" maxlength="63"></div><div class="field"><label>Device name</label><input id="setupName" value="My PulseBar" maxlength="32" required></div><div class="field"><label>Time zone</label><select id="setupTimezone"><option value="UTC0">UTC</option><option value="IST-5:30">India</option><option value="EST5EDT,M3.2.0,M11.1.0">US Eastern</option><option value="PST8PDT,M3.2.0,M11.1.0">US Pacific</option><option value="GMT0BST,M3.5.0/1,M10.5.0">United Kingdom</option><option value="CET-1CEST,M3.5.0,M10.5.0/3">Central Europe</option></select></div><p class="error" id="setupError"></p><button class="primary">Connect PulseBar</button></form></div>
<main class="shell"><header class="top"><div class="brand"><i></i><span id="deviceName">My PulseBar</span></div><div class="top-right"><span class="pill" id="network">Connecting</span><svg id="wifiIcon" class="wifi" viewBox="0 0 28 22" aria-label="Wi-Fi signal"><path d="M2 7c7-6 17-6 24 0M6 12c5-4 11-4 16 0M11 17c2-2 4-2 6 0M14 20h0"/></svg></div></header>
<section class="layout"><section class="card"><div class="eyebrow">Live display</div><div class="matrix" id="matrix"></div><label class="eyebrow">Brightness <span id="brightnessValue">48</span></label><div class="brightness"><input id="brightness" type="range" min="1" max="255" value="48"><button id="applyBrightness">Apply</button></div><div class="display-tools"><div class="tool"><span class="eyebrow">Display colour</span><button id="paletteToggle">Choose colour</button></div><label class="tool"><span class="eyebrow">Scene duration</span><select id="sceneDuration"><option value="2">2 seconds</option><option value="3">3 seconds</option><option value="5">5 seconds</option><option value="8">8 seconds</option><option value="10">10 seconds</option><option value="15">15 seconds</option><option value="30">30 seconds</option><option value="60">60 seconds</option></select></label></div><div class="palette" id="palette"></div></section>
<section class="card"><div class="eyebrow">Scene Rotation</div><p class="hint">Selected screens appear in the live preview and cycle on PulseBar. Stopwatch activates only from its physical button.</p><div id="sceneOptions"></div><button class="primary" id="savePlaylist">Save rotation</button></section></section>
<nav class="platforms"><button class="platform active" data-platform="youtube" aria-label="YouTube"></button><button class="platform" data-platform="facebook" aria-label="Facebook"></button><button class="platform" data-platform="instagram" aria-label="Instagram"></button></nav>
<section class="card"><div class="eyebrow" id="providerTitle">Connect YouTube channel</div><div class="field"><label id="accountUrlLabel">Channel link</label><input id="accountUrl" type="url" placeholder="https://youtube.com/@yourchannel"></div><div class="field"><label id="credentialLabel">YouTube Data API key</label><input id="apiCredential" type="password" autocomplete="off" placeholder="Stored only on this PulseBar"></div><button class="primary" id="connectAccount">Save and connect</button><p class="hint" id="providerStatus">Add the channel link and API key.</p></section></main>
<script>
const $=id=>document.getElementById(id),api=async(path,options)=>{const r=await fetch(path,options),j=await r.json();if(!j.success)throw Error(j.error?.message||'Request failed');return j.data};
const matrix=$('matrix');for(let i=0;i<256;i++){const p=document.createElement('i');p.className='px';matrix.append(p)}
const digits={0:['111','101','101','101','111'],1:['010','110','010','010','111'],2:['111','001','111','100','111'],3:['111','001','111','001','111'],4:['101','101','111','001','001'],5:['111','100','111','001','111'],6:['111','100','111','101','111'],7:['111','001','001','001','001'],8:['111','101','111','101','111'],9:['111','101','111','001','111']};
function sceneValue(id){if(id==='time'){const n=new Date(),hour=playlistData.clockFormat==='12'?(n.getHours()%12||12):n.getHours();return String(hour).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')}return {youtubeSubscribers:'12480',youtubeViews:'2384',instagramFollowers:'21600',instagramViews:'5100',facebookFollowers:'8320',facebookViews:'9140'}[id]||'0'}
function sceneColor(id,x){if(id.startsWith('youtube'))return'#ff0033';if(id.startsWith('facebook'))return'#1877f2';if(id.startsWith('instagram')){const stops=[[255,45,149],[174,52,255],[92,45,145]],t=Math.max(0,Math.min(1,x/31)),half=t<.5?t*2:(t-.5)*2,a=t<.5?stops[0]:stops[1],b=t<.5?stops[1]:stops[2],rgb=a.map((v,i)=>Math.round(v+(b[i]-v)*half));return`rgb(${rgb.join(',')})`}return getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()||'#ff4d91'}
function lightPixel(p,id,x){if(!p)return;const color=sceneColor(id,x);p.classList.add('on');p.style.background=color;p.style.boxShadow=`0 0 7px ${color}`}function metricIcon(id,pixels,views,x0){const rows=views?['01110','10101','01110']:['010','000','111','111'],y0=views?2:2;rows.forEach((row,y)=>[...row].forEach((v,x)=>{if(v==='1')lightPixel(pixels[(y0+y)*32+x0+x],id,x0+x)}))}function drawScene(id,pixels=[...matrix.children]){pixels.forEach(p=>{p.classList.remove('on');p.style.background='';p.style.boxShadow='' });const value=sceneValue(id),views=id.endsWith('Views'),metric=id!=='time',numberWidth=value.length*4-1,iconWidth=views?5:3,groupWidth=metric?numberWidth+iconWidth+2:numberWidth,start=Math.max(0,Math.floor((32-groupWidth)/2)),numberX=metric&&views?start+iconWidth+2:start;let x=numberX;for(const c of value){if(c==':'){[[x,2],[x,4]].forEach(([a,b])=>lightPixel(pixels[b*32+a],id,a));x+=2}else if(digits[c]){digits[c].forEach((row,y)=>[...row].forEach((v,b)=>{if(v=='1')lightPixel(pixels[(y+1)*32+x+b],id,x+b)}));x+=4}}if(metric)metricIcon(id,pixels,views,views?start:start+numberWidth+2)}
let lastSceneChange=Date.now();function drawSelectedScene(){const enabled=playlistData.scenes.filter(s=>s.enabled);drawScene(enabled.length?enabled[loopIndex%enabled.length].id:'time')}setInterval(()=>{const enabled=playlistData.scenes.filter(s=>s.enabled),duration=(playlistData.durationSeconds||8)*1000;if(enabled.length&&Date.now()-lastSceneChange>=duration){loopIndex=(loopIndex+1)%enabled.length;lastSceneChange=Date.now();drawSelectedScene()}},250);setInterval(drawSelectedScene,1000);
const groups=[{name:'Live Time',preview:'time',items:[['time','Live time']]},{name:'YouTube',preview:'youtubeSubscribers',items:[['youtubeSubscribers','Subscriber counter'],['youtubeViews','Views count']]},{name:'Instagram',preview:'instagramFollowers',items:[['instagramFollowers','Followers count'],['instagramViews','Views count']]},{name:'Facebook',preview:'facebookFollowers',items:[['facebookFollowers','Followers count'],['facebookViews','Views count']]}];let playlistData={clockFormat:'24',scenes:[]},loopIndex=0;
function miniPixels(id){return `<div class="mini" data-preview="${id}">${'<i></i>'.repeat(256)}</div>`}function renderOptions(){const enabled=Object.fromEntries(playlistData.scenes.map(s=>[s.id,s.enabled]));$('sceneOptions').innerHTML=groups.map((g,index)=>`<section class="category"><div class="category-head"><div><h3>${g.name}</h3>${g.items.map(([id,label])=>`<label class="choice"><input type="checkbox" data-scene="${id}" ${enabled[id]?'checked':''}>${label}</label>`).join('')}${index===0?`<div class="format"><label class="choice"><input type="radio" name="clockFormat" value="12" ${playlistData.clockFormat==='12'?'checked':''}>12 hr</label><label class="choice"><input type="radio" name="clockFormat" value="24" ${playlistData.clockFormat!=='12'?'checked':''}>24 hr</label></div>`:''}</div>${miniPixels(g.preview)}</div></section>`).join('');document.querySelectorAll('.mini').forEach(m=>drawScene(m.dataset.preview,[...m.children]))}
async function loadPlaylist(){playlistData=await api('/api/v1/playlist');$('sceneDuration').value=playlistData.durationSeconds||8;renderOptions();drawSelectedScene()}
$('sceneDuration').onchange=()=>{playlistData.durationSeconds=+$('sceneDuration').value;lastSceneChange=Date.now()};$('savePlaylist').onclick=async()=>{const scenes=[...document.querySelectorAll('[data-scene]')].map(i=>({id:i.dataset.scene,enabled:i.checked})),clockFormat=document.querySelector('[name=clockFormat]:checked')?.value||'24',durationSeconds=+$('sceneDuration').value;playlistData=await api('/api/v1/playlist',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenes,clockFormat,durationSeconds})});loopIndex=0;lastSceneChange=Date.now();renderOptions();drawSelectedScene()};loadPlaylist();
const logos={youtube:'<svg viewBox="0 0 24 24"><rect x="1" y="4" width="22" height="16" rx="5" fill="#ff0033"/><path fill="white" d="m10 8 6 4-6 4z"/></svg>',facebook:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="11" fill="#1877f2"/><path fill="white" d="M14 20v-7h2l.4-3H14V8.5c0-1 .4-1.5 1.6-1.5h1V4.4c-.5-.1-1.3-.2-2.2-.2-2.2 0-3.7 1.4-3.7 4V10H8v3h2.7v7z"/></svg>',instagram:'<svg viewBox="0 0 24 24"><rect x="2" y="2" width="20" height="20" rx="6" fill="#d62976"/><circle cx="12" cy="12" r="4" fill="none" stroke="white" stroke-width="2"/><circle cx="18" cy="6" r="1.2" fill="white"/></svg>'};
let platform='youtube',accounts={};document.querySelectorAll('.platform').forEach(b=>{b.innerHTML=logos[b.dataset.platform];b.onclick=()=>selectPlatform(b.dataset.platform)});function selectPlatform(p){platform=p;document.querySelectorAll('.platform').forEach(b=>b.classList.toggle('active',b.dataset.platform==p));const name={youtube:'YouTube channel',facebook:'Facebook page',instagram:'Instagram profile'}[p],credentialName={youtube:'YouTube Data API key',facebook:'Meta Page access token',instagram:'Meta Instagram access token'}[p];$('providerTitle').textContent='Connect '+name;$('credentialLabel').textContent=credentialName;$('apiCredential').value='';$('apiCredential').placeholder=accounts[p]?.authorized?'Configured — enter only to replace':'Stored only on this PulseBar';$('accountUrl').value=accounts[p]?.url||'';$('accountUrl').placeholder='https://'+p+'.com/your'+(p=='facebook'?'page':'profile');$('providerStatus').textContent=accounts[p]?.status||'Add the public link and API credentials.'}async function loadAccounts(){accounts=await api('/api/v1/accounts');selectPlatform(platform)}$('connectAccount').onclick=async()=>{try{await api('/api/v1/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({platform,url:$('accountUrl').value,credential:$('apiCredential').value})});loadAccounts()}catch(e){$('providerStatus').textContent=e.message}};loadAccounts();
const colors=['#FF4D91','#FF3B30','#FF9500','#FFD60A','#34C759','#55DFFF','#0A84FF','#BF5AF2','#FFFFFF','#FF9F7A','#64D2FF','#8E8E93'];$('palette').innerHTML=colors.map(c=>`<button class="swatch" style="background:${c}" data-color="${c}" aria-label="Use ${c}"></button>`).join('');$('paletteToggle').onclick=()=>$('palette').classList.toggle('open');$('palette').onclick=e=>{const c=e.target.dataset.color;if(!c)return;document.documentElement.style.setProperty('--accent',c);api('/api/v1/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'color',value:c})});renderOptions();drawSelectedScene();$('palette').classList.remove('open')};$('brightness').oninput=()=>$('brightnessValue').textContent=$('brightness').value;$('applyBrightness').onclick=()=>api('/api/v1/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'brightness',value:+$('brightness').value})});
async function status(){try{const d=await api('/api/v1/status');$('deviceName').textContent=d.name;$('network').textContent=d.wifi?d.ssid:'Setup mode';$('brightness').value=d.brightness;$('brightnessValue').textContent=d.brightness;$('wifiIcon').className.baseVal='wifi '+(d.wifi?(d.rssi>-67?'good':'weak'):'');$('wifiIcon').style.opacity=d.wifi?'1':'.35';if(d.color)document.documentElement.style.setProperty('--accent',d.color);if(d.setupRequired&&!$('setup').classList.contains('show')){$('setup').classList.add('show');loadNetworks()}}catch(e){$('network').textContent='Offline'}}status();setInterval(status,3000);
async function loadNetworks(){try{const list=await api('/api/v1/network/scan');$('setupSsid').innerHTML=list.map(n=>`<option value="${n.ssid}">${n.ssid}</option>`).join('')}catch(e){$('setupError').textContent=e.message}}$('setupForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/v1/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:$('setupSsid').value,password:$('setupPassword').value,deviceName:$('setupName').value,timezone:$('setupTimezone').value})});$('setupError').textContent='Saved. Reconnect to home Wi-Fi and open pulsebar.local'}catch(x){$('setupError').textContent=x.message}};
</script></body></html>)HTML";
